#!/bin/bash

# Define the script and the base directory
SCRIPT="TBBE.py"
BASE_DIR="/Users/joesouber/XGBoost_TBBE"

# Function to run the script in the background for a given directory
run_script() {
    DIR=$1
    cd $BASE_DIR/$DIR/DeepBettor_BBE/TBBE_OD_XGboost/Application
    nohup nice python3 $SCRIPT > "output.log" 2>&1 &
}

# Run the script for each core directory
run_script "Core1"
run_script "Core2"
run_script "Core3"
run_script "Core4"
run_script "Core5"
run_script "Core6"
run_script "Core7"
run_script "Core8"

# Wait for all background processes to finish
wait

